name:                memo-utils
version:             0.1.0.0
github:              "githubuser/memo-utils"
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "2018 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/y-usuzumi/memo/memo-utils#readme>

dependencies:
- base >= 4.7 && < 5
- deriving-compat
- directory
- filepath
- recursion-schemes
- optparse-applicative
- template-haskell

default-extensions:
- DeriveAnyClass
- DeriveFunctor
- RecordWildCards
- RecursiveDo
- StandaloneDeriving
- QuasiQuotes
- TemplateHaskell

library:
  source-dirs: src

executables:
  memo-utils-gen-toc:
    main:                ReadmeGen/Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memo-utils

tests:
  memo-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memo-utils
